Startup update
KomodoPlatform/atomicDEX-Desktop pull request #1055
Opened 2021-06-30 15:40 UTC by ssakone

2021-07-01 04:43 UTC, Milerius commented
> ### Login update step
> * [x]  Startup Page
> * [x]  Wallet Login
> * [ ]  New Wallet registration
> * [ ]  Wallet Restoration
> * [x]  Loading ui
> 
> ![image](https://user-images.githubusercontent.com/39985611/123991157-0078e700-d9ba-11eb-8fe5-c02b055098b6.png)
> ![image](https://user-images.githubusercontent.com/39985611/123991484-4a61cd00-d9ba-11eb-87bd-7b151816427d.png)
> ![image](https://user-images.githubusercontent.com/39985611/123991607-649bab00-d9ba-11eb-8278-64e8fdc8c42e.png)

Got a first warning: `[06:41:26] [warning] [main.prerequisites.hpp:126] [5020275]: qrc:/atomic_defi_design/qml/Components/SetupPage.qml:15:5: Unable to assign [undefined] to QString
`

2021-07-01 04:45 UTC, Milerius requested changes

2021-07-01 04:45 UTC, Milerius commented on atomic_defi_design/qml/Components/DexAppButton.qml
> +            left: parent.horizontalAlignment == Qt.AlignLeft? parent.left : undefined
Coding style

2021-07-01 04:45 UTC, Milerius commented on atomic_defi_design/qml/Components/DexAppButton.qml
> +            iconSize: _label.font.pixelSize+2
coding style

2021-07-01 04:45 UTC, Milerius commented on atomic_defi_design/qml/Components/DexAppTextField.qml
> +	    border.width: input_field.focus? 1 : 0
coding style

2021-07-01 04:45 UTC, Milerius commented on atomic_defi_design/qml/Components/DexAppTextField.qml
> +			Layout.preferredWidth: leftWidth!==-1? leftWidth : _title_label.implicitWidth+2
coding style

2021-07-01 04:45 UTC, Milerius commented on atomic_defi_design/qml/Components/DexAppTextField.qml
> +			visible: rightText!==""
coding style

2021-07-01 04:45 UTC, Milerius commented on atomic_defi_design/qml/Screens/FirstLaunch.qml
> +                                width: mouse_area.containsMouse? parent.width : 0
coding style

2021-07-01 04:45 UTC, Milerius commented on atomic_defi_design/qml/Screens/InitialLoading.qml
> +            Layout.rightMargin: Layout.leftMargin*0.75
coding style

2021-07-01 04:45 UTC, Milerius commented on atomic_defi_design/qml/Screens/Login.qml
> +                Layout.preferredWidth: _nextRow.implicitWidth+40
coding style

2021-07-01 10:41 UTC, ssakone commented on atomic_defi_design/qml/Screens/InitialLoading.qml
> +            Layout.rightMargin: Layout.leftMargin*0.75
old code

2021-07-02 01:32 UTC, smk762 commented
Login with existing user working ok.
![image](https://user-images.githubusercontent.com/35845239/124207434-1ac8d700-db18-11eb-9241-0d9005f4bec5.png)

Not sure why the user left section / icon is faded compared to the password icon?
Or what the purpose of this bit between the field is - 
![image](https://user-images.githubusercontent.com/35845239/124207511-451a9480-db18-11eb-9a5d-993425889a03.png)

2021-07-02 09:58 UTC, ssakone commented
> Login with existing user working ok.
> ![image](https://user-images.githubusercontent.com/35845239/124207434-1ac8d700-db18-11eb-9241-0d9005f4bec5.png)
> 
> Not sure why the user left section / icon is faded compared to the password icon?
> Or what the purpose of this bit between the field is -
> ![image](https://user-images.githubusercontent.com/35845239/124207511-451a9480-db18-11eb-9a5d-993425889a03.png)

User field is not is not editable and i belive i need to change icon, because its not user but wallet

2021-07-03 21:35 UTC, tonymorony commented
Great progress, current feedback:

1) Don't allow multiline on seed phrase input, that's potentially very dangerous (user will generate different wallet from his seed if even single `/n` will be added):

<img width="630" alt="Screenshot 2021-07-04 at 03 26 56" src="https://user-images.githubusercontent.com/24797699/124367286-b7ee5180-dc77-11eb-8fb9-b79b272b79a4.png">

2)  Show only 4 words as an option here, otherwise, it's too much time to find a needed word in a huge list and it's faster just type:

![image](https://user-images.githubusercontent.com/24797699/124367315-f3891b80-dc77-11eb-9bdf-34f47e66aa1f.png)

3) There is no login button at the moment and no indication that the user input not correct password

![image](https://user-images.githubusercontent.com/24797699/124367339-1ca9ac00-dc78-11eb-89b1-eb6ccaeaebd4.png)

2021-07-03 21:53 UTC, tonymorony submitted a review, later dismissed
left feedback from the testing session above, please pay special attention to seed validation it's a critical component of the app

2021-07-05 12:34 UTC, Milerius requested changes
After the first try - 2nd word of seed was asked twice during the seed validation.

2021-07-05 12:37 UTC, Milerius commented
Few remarks

- Custom seed should allow any type of seed
- When custom seed is not ticked the valid seed are either 12 or 24 words seed
- If a default wallet is already selected, clicking on return goes back to this specific page


https://user-images.githubusercontent.com/21139416/124472552-8e7c1580-dd9e-11eb-9751-c52cb20b1460.mov

2021-07-06 06:04 UTC, smk762 commented
> 1. I think it might be worth adding wallet name somewhere on this page
> 
> ![image](https://user-images.githubusercontent.com/24797699/124367563-0d2b6280-dc7a-11eb-8845-8eb1b166b7e3.png)

Something like this would be nice
![image](https://user-images.githubusercontent.com/35845239/124550331-175c8500-de63-11eb-8f54-dd5b78267914.png)

2021-07-06 06:44 UTC, smk762 commented
Re: https://github.com/KomodoPlatform/atomicDEX-Desktop/actions/runs/1001035197

- Confirm newline in wallet restore textarea issue resolved (both custom and non-custom) :heavy_check_mark: 

- non-custom seed validation incomplete. :stop_sign: 
  - should not be allowing leading space before first word (ideally not for custom seed either)
  - should not be allowing trailing space after last word (ideally not for custom seed either)
  - should not be allowing capitals as input
  - should not be allowing special chars as input
  - should not be allowing non 12/24 word count (if trailing space)
  - should not be allowing words are not in BIP39 wordlist
  
![image](https://user-images.githubusercontent.com/35845239/124552210-ce5a0000-de65-11eb-9c52-2dda08b61b57.png)

  - Word selection for new seed 4 word choice confirmation :heavy_check_mark: 
    - **BUT** user can just spam selection until they get it right, i.e. not forced to write down.
    - Suggest failed attempt changes number of word to be confirmed, and 3 failed attempts aborts wallet creation.

https://user-images.githubusercontent.com/35845239/124552797-91423d80-de66-11eb-82ac-6024b69aa476.mp4
  
> ...no indication that the user input not correct password
- Confirm failed password effect (shake and color change) triggered on "connect" button press if incorrect. :heavy_check_mark: 

> There is a bug if click on the same translation flag twice:
- Confirm resolved :heavy_check_mark: 

> If a default wallet is already selected, clicking on return goes back to this specific page 
- Unable to replicate, assume resolved.

2021-07-06 10:58 UTC, ssakone commented
- Enhance Seed Verification & improve user interaction
- Add Bip39Wordlist Checking
- Change login screen display to new splash login
- improve login page

2021-07-06 14:58 UTC, tonymorony commented on atomic_defi_design/qml/Screens/RecoverSeed.qml
> +                id: big39Checker
it's a bip, not big :)

2021-07-07 05:19 UTC, smk762 commented
Password where visible is slightly too large for input area - suggest slight font size reduction
![image](https://user-images.githubusercontent.com/35845239/124702903-e001dd00-df23-11eb-9f35-0915109dcd31.png)

Appears that incorrect password no longer alerts user when input
```
[13:08:46] [info] [app.cpp:644] [540000]: Application active
[13:08:50] [info] [qt.wallet.manager.cpp:271] [540000]: qt_wallet_manager::login
[13:08:50] [info] [qt.wallet.manager.cpp:183] [540000]: Loading wallet configuration: cswm
[13:08:50] [info] [qt.wallet.manager.cpp:197] [540000]: wallet_cfg: {
    "name": "cswm"
}
[13:08:50] [debug] [security.utilities.cpp:52] [540000]: derive_password l52 f[security.utilities.cpp]
[13:08:50] [info] [security.utilities.cpp:65] [540000]: Key generated successfully
[13:08:50] [debug] [security.utilities.cpp:100] [540000]: decrypt l100 f[security.utilities.cpp]
[13:08:50] [warning] [qt.wallet.manager.cpp:313] [540000]: Wrong password, or the seed file is corrupted.
[13:08:50] [debug] [main.prerequisites.hpp:120] [540000]: Failed: Login
[13:08:50] [warning] [main.prerequisites.hpp:126] [540000]: qrc:/atomic_defi_design/qml/Screens/FirstLaunch.qml:32: Error: Invalid write to global property "text_error"
```

When entering password, but then cancelling and returning to select a different wallet, the previously entered password is still in the input. Hidden/Shown state is also persisting. On selection of a wallet, this input should be reset to empty and hidden.

https://user-images.githubusercontent.com/35845239/124703975-e09b7300-df25-11eb-9ed9-fd5d632a4d8f.mp4

2021-07-07 05:30 UTC, smk762 commented
![image](https://user-images.githubusercontent.com/35845239/124704574-df1e7a80-df26-11eb-89da-3e1147932497.png)

`Incorrect seed try again` is ambiguous. Suggest `BIP39 seed validation failed, try again or select 'Allow custom seed'`

2021-07-08 11:49 UTC, Milerius commented
Please remove the word checker list and used the function that is present for mnemonic validation: 

`Q_INVOKABLE static bool        mnemonic_validate(const QString& entropy);`

`./qml/Screens/RecoverSeed.qml:157:                             (allow_custom_seed.checked || API.app.wallet_mgr.mnemonic_validate(input_seed.field.text))`

2021-07-08 11:58 UTC, tonymorony commented on atomic_defi_design/qml/Components/DexBip39WordListChecker.qml
> +import QtQuick 2.15
there is mnemonic_validate function for that https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/atomic_defi_design/qml/Screens/RecoverSeed.qml#L157

2021-07-09 06:16 UTC, smk762 commented
Slight button overflow when error message appears on wallet recover- 
![image](https://user-images.githubusercontent.com/35845239/125032129-170cf580-e0c0-11eb-8d17-a9d1d799c9b9.png)

Only happens on first try, subsequent attempts the button is within panel.

2021-07-09 06:18 UTC, smk762 commented
`Cotinue` should be `Continue`
![image](https://user-images.githubusercontent.com/35845239/125032401-7d921380-e0c0-11eb-9dd7-ab93f6b3e46d.png)

2021-07-09 06:26 UTC, smk762 commented
"View Seed" for newly created wallet is incomplete (created thru "new wallet" button).

![image](https://user-images.githubusercontent.com/35845239/125032838-1c1e7480-e0c1-11eb-8ddb-859c56131378.png)

Checked older wallet, full seed was on display. Restored wallet (with custom seed) also displayed ok.

2021-07-09 07:11 UTC, Milerius commented
> "View Seed" for newly created wallet is incomplete (created thru "new wallet" button).
> 
> ![image](https://user-images.githubusercontent.com/35845239/125032838-1c1e7480-e0c1-11eb-8ddb-859c56131378.png)
> 
> Checked older wallet, full seed was on display. Restored wallet (with custom seed) also displayed ok.
> 
> **Very lucky I caught this**
> I had not thought to check that until today. Anything related to seed / passphrase / private key needs to be handled with care and checked more often than Santa Claus' list.
> 
> If merged and found by a user unable to recover account, or running an account with a single word seed which was hacked, there would be some serious egg on our face.
> 
> In this case, I checked using `life` as a custom seed - it gave same address, which makes it a massively insecure wallet.
> 
> Perhaps we should implement some standards for custom seeds so that there is no chance of a seed less than a certain level of entropy.

I do agree on wallet creation for additional security check, like internal validate from my side (i was expecting that `mnemonic_validate` will be called before final validation by front end, because in this case we can show an error in the front-end, that's why this function was exposed in a nice way in order to be used in front end even before the wallet creation, not only on restore - pretty sure it's was the case before.

2021-07-09 07:23 UTC, Milerius commented on atomic_defi_design/qml/Components/DexAppTextArea.qml
> +    property alias value: input_field.text
coding style / alignment

2021-07-09 07:24 UTC, Milerius commented on atomic_defi_design/qml/Components/DexAppTextField.qml
> +    property alias value: input_field.text
coding style / alignment

2021-07-09 07:24 UTC, Milerius commented on atomic_defi_design/qml/Components/DexAppTextField.qml
> +		id: _background
coding style / alignment

2021-07-09 07:28 UTC, Milerius commented on atomic_defi_design/qml/Screens/RecoverSeed.qml
>      property var postConfirmSuccess: () => {}
postConfirmSuccess should clean the seed and the password from memory.

2021-07-09 07:38 UTC, smk762 commented
Sometimes when logging out, It goes back to this screen

![image](https://user-images.githubusercontent.com/35845239/125041472-60af0d80-e0cb-11eb-9a76-e599eca2e70f.png)

no wallet name, so not sure what I'm logging in to.

This only happens sometimes, have been unable to catch exact steps to replicate it every time.

2021-07-09 07:39 UTC, Milerius commented
> Sometimes when logging out, It goes back to this screen
> 
> ![image](https://user-images.githubusercontent.com/35845239/125041472-60af0d80-e0cb-11eb-9a76-e599eca2e70f.png)
> 
> no wallet name, so not sure what I'm logging in to.
> 
> This only happens sometimes, have been unable to catch exact steps to replicate it every time. Should return to the wallet selection page every time.

Yeah it's should always go back to the wallet selection not this page, good catch

2021-07-09 11:17 UTC, ca333 commented
@ssakone please do validate and test your code **BEFORE** commit/push!

2021-07-09 11:35 UTC, ssakone commented
> @ssakone please do validate and test your code **BEFORE** commit/push!

I'm sorry for the inconvenience and will be even more careful.

2021-07-09 11:44 UTC, Milerius commented
> Slight button overflow when error message appears on wallet recover-
> ![image](https://user-images.githubusercontent.com/35845239/125032129-170cf580-e0c0-11eb-8d17-a9d1d799c9b9.png)
> 
> Only happens on first try, subsequent attempts the button is within panel.

Let's check this overflow and the logout problem so we can maybe merge it afterwards @ssakone if you have any doubt or question please ask on the keybase channel

2021-07-09 17:07 UTC, ssakone commented
@tonymorony 
![image](https://user-images.githubusercontent.com/39985611/125113273-f6e93080-e0d7-11eb-8c9f-890099d79aea.png)
about when user have lot of wallet like me, is there anything to delete some wallet directly or will you have to connect to each one to delete?

2021-07-10 03:56 UTC, Milerius commented
> @tonymorony
> ![image](https://user-images.githubusercontent.com/39985611/125113273-f6e93080-e0d7-11eb-8c9f-890099d79aea.png)
> about when user have lot of wallet like me, is there anything to delete some wallet directly or will you have to connect to each one to delete?

could be done into a separate pr

2021-07-10 08:24 UTC, smk762 commented
overflow button on nonBIP39 seed fixed :heavy_check_mark: 
new wallet full seed phrase issue fixed :heavy_check_mark: 
`continue` spelling fixed :heavy_check_mark: 
Password not clearing if cancelling to select different wallet :crab: 

https://user-images.githubusercontent.com/35845239/125156999-01b8c980-e19b-11eb-9b43-077d839d6dc4.mp4

2021-07-11 03:02 UTC, smk762 commented
Password clearing when cancelling to select different wallet :heavy_check_mark:

2021-07-11 05:17 UTC, Milerius commented on atomic_defi_design/qml/Screens/NewUser.qml
> +                field.placeholderText: qsTr("Cofirm password")
Confirm password

2021-07-11 05:18 UTC, smk762 submitted a review, later dismissed

2021-07-11 05:18 UTC, Milerius approved these changes

2021-07-11 05:18 UTC, Milerius commented
Final review @smk762 @tonymorony plz

2021-07-12 06:33 UTC, smk762 approved these changes

2021-07-12 10:55 UTC, tonymorony commented
is it intended that these icons are blured and unclickable?

<img width="1238" alt="Screenshot 2021-07-12 at 16 54 00" src="https://user-images.githubusercontent.com/24797699/125276330-ec29d800-e331-11eb-9d7b-153f436ca017.png">

2021-07-12 10:57 UTC, Milerius commented
> is it intended that these icons are blured and unclickable?
> 
> <img alt="Screenshot 2021-07-12 at 16 54 00" width="1238" src="https://user-images.githubusercontent.com/24797699/125276330-ec29d800-e331-11eb-9d7b-153f436ca017.png">

Yes, it's the effect

2021-07-12 11:16 UTC, tonymorony approved these changes

2021-07-12 11:17 UTC, merged