fix show seed modal
KomodoPlatform/atomicDEX-Desktop pull request #1438
Opened 2021-11-19 12:15 UTC by smk762

- recolor qrcode / copy icons so they are visible in light/dark mode.
- fix add pointer cursor on hover over icons
- add "copied to clipboard" notification on click
- change password field to use DexAppPasswordField so show/hide button color is visible in dark/light mode.

2021-11-20 05:59 UTC, tonymorony approved these changes

2021-11-20 10:17 UTC, smk762 commented
- add corner rounding to warning and words
- add background to words
- update next button
- fix wallet name input field background
- restore copy button visibility


before
![image](https://user-images.githubusercontent.com/35845239/142722731-40e436a7-a8ed-437d-8a06-bd8aa0838229.png)


after
![image](https://user-images.githubusercontent.com/35845239/142722702-eb2833ba-b761-48b1-b8ad-2ea7abeb4ccd.png)

2021-11-20 12:18 UTC, smk762 commented
before
![image](https://user-images.githubusercontent.com/35845239/142725627-db72502d-48b4-4f5e-ad09-7cadfbaea782.png)
![image](https://user-images.githubusercontent.com/35845239/142725655-4cc1d434-7c43-47b9-aae9-eb14720978bf.png)


after
![image](https://user-images.githubusercontent.com/35845239/142725595-e01b4d22-794e-4f69-a5c8-e8b3fed80cc0.png)
![image](https://user-images.githubusercontent.com/35845239/142726006-b54b1c28-cf46-48ea-b78d-02d674284f41.png)

2021-11-20 13:07 UTC, smk762 commented
Resolved #3 in https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1427#issue-1053383827

before
![image](https://user-images.githubusercontent.com/35845239/142727374-f29c83da-7ab5-4f73-820c-1386ec2d970a.png)
![image](https://user-images.githubusercontent.com/35845239/142727398-4fa62e8e-a19e-4d3e-a80d-064f2c691922.png)


after
![image](https://user-images.githubusercontent.com/35845239/142727323-bfe878d5-5d59-40a8-97d4-7324e15bbb5f.png)
![image](https://user-images.githubusercontent.com/35845239/142727350-1dc92857-e5cc-4450-9c60-391571b69c29.png)

2021-11-21 04:15 UTC, smk762 commented
Resolves #8 in https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1427#issuecomment-968682835

Before
![image](https://user-images.githubusercontent.com/35845239/142749326-c5ed653c-d33f-419e-9b28-b3aea89c0a28.png)


After
![image](https://user-images.githubusercontent.com/35845239/142749310-da8110d3-3a8e-40bc-ac20-52d92d968d44.png)

2021-11-21 11:10 UTC, SylEze requested changes

2021-11-21 11:10 UTC, SylEze commented on atomic_defi_design/Dex/Components/DexAppPasswordField.qml
> +        border.color: _inputPassword.focus ? DexTheme.accentColor : DexTheme.rectangleBorderColor
`DexTheme` is deprecated, use:

```qml
import Dex.Themes 1.0 as Dex

Dex.CurrentTheme.whateverColor
```

2021-11-21 11:10 UTC, SylEze commented on atomic_defi_design/Dex/Components/DexAppTextField.qml
> +        color: DexTheme.backgroundColor
Same as above

2021-11-21 11:10 UTC, SylEze commented on atomic_defi_design/Dex/Components/TextAreaWithTitle.qml
> +                color: DexTheme.accentColor
Same as above

2021-11-21 11:10 UTC, SylEze commented on atomic_defi_design/Dex/Screens/Startup/NewWallet.qml
> +                        color: Style.colorWhite0
Are you sure this will work on every theme ?

2021-11-21 11:10 UTC, SylEze commented on atomic_defi_design/Dex/Screens/Startup/NewWallet.qml
> +                        color: Style.colorWhite0
Are you sure this will work on every theme ?

2021-11-21 11:10 UTC, SylEze commented on atomic_defi_design/Dex/Screens/Startup/NewWallet.qml
> +                        icon.color: DexTheme.foregroundColor
`Dex.CurrentTheme`

2021-11-21 11:10 UTC, SylEze commented on atomic_defi_design/Dex/Screens/Startup/NewWallet.qml
> +                                color: Style.colorWhite0
Are you sure this will work on every theme ?

2021-11-21 11:10 UTC, SylEze commented on atomic_defi_design/Dex/Screens/Startup/NewWallet.qml
> +                                color: Dex.CurrentTheme.accentColor
`Dex.CurrentTheme`

2021-11-21 13:10 UTC, smk762 commented on atomic_defi_design/Dex/Components/DexAppPasswordField.qml
> +        border.color: _inputPassword.focus ? DexTheme.accentColor : DexTheme.rectangleBorderColor
updated

2021-11-21 13:10 UTC, smk762 commented on atomic_defi_design/Dex/Components/DexAppTextField.qml
> +        color: DexTheme.backgroundColor
updated

2021-11-21 13:10 UTC, smk762 commented on atomic_defi_design/Dex/Components/TextAreaWithTitle.qml
> +                color: DexTheme.accentColor
updated

2021-11-21 13:11 UTC, smk762 commented on atomic_defi_design/Dex/Screens/Startup/NewWallet.qml
> +                        icon.color: DexTheme.foregroundColor
updated

2021-11-21 13:11 UTC, smk762 commented on atomic_defi_design/Dex/Screens/Startup/NewWallet.qml
> +                        icon.color: DexTheme.foregroundColor
updated

2021-11-21 14:53 UTC, merged