Update new Popup Manager
KomodoPlatform/atomicDEX-Desktop pull request #1447
Opened 2021-11-22 13:15 UTC by ssakone

2021-11-22 15:12 UTC, SylEze requested changes

2021-11-22 15:12 UTC, SylEze commented on atomic_defi_design/Dex/Components/DexPopupManager.qml
> +Popup {
Coding style

2021-11-22 15:12 UTC, SylEze commented on atomic_defi_design/Dex/Components/DexPopupManager.qml
> +import QtQuick 2.15
Remove `Dex` prefix from file name

2021-11-23 08:40 UTC, smk762 commented
Figma on the right
![image](https://user-images.githubusercontent.com/35845239/142990302-8aa36b80-25cb-4541-8ab0-0572b9a8aae6.png)
- button wording
- button state (always enabled in app)
- input field background darkness

Figma on the right
![image](https://user-images.githubusercontent.com/35845239/142991090-0152faf3-4b58-45f7-8fe2-75766c4d3452.png)
- field input icon misaligned, backfround darkness
- fonts
- button state (always enabled in app)

I think "Cancel" is actually a better choice than "close" in the above cases (disagree with figma)

not in figma
![image](https://user-images.githubusercontent.com/35845239/142991846-ed1932c7-f627-4fd4-b9b2-c4a54b075369.png)
- "Wallet status" should be bolder
- Change to "{wallet_name} password is incorrect" (remove "entered", it is not needed and reads funny)
- "Yes" should be "Ok"

Figma on right
![image](https://user-images.githubusercontent.com/35845239/142992315-6dbefc0e-4b9c-4103-953b-33cb2741bcde.png)
- Font weight and alignment

Figma on right
![image](https://user-images.githubusercontent.com/35845239/142992625-0c69b97e-ac16-4def-a2de-d76eea12af32.png)
- Font weight and alignment
- No button
- dot count at top

Figma on right
![image](https://user-images.githubusercontent.com/35845239/142992704-cab4c37a-c563-4880-9bf9-c5917aa483ca.png)
- Font weight and alignment
- No button
- dot count at top

Pls let me know if I'm missing anywhere else this is used.

2021-11-23 11:35 UTC, ssakone commented
@smk762  not able to find screen 3, and screen 5, 6 is another type of dialogue, let me sync with  syl about that update.

2021-11-23 11:37 UTC, smk762 commented
Screen 3 is if you input wrong password when attempting to delete wallet

2021-11-23 11:43 UTC, ssakone commented
should done but, check title bold level now, i think its not okay

2021-11-23 11:46 UTC, ssakone commented
For screen two i think color correction will fix it, @SylEze help!

2021-11-28 16:26 UTC, tonymorony requested changes
looks quite acceptable to me, just would be great to use the same color for input fields as other parts of the app, so we'll be able to change it globally across the app for better contrast and/or during other skins creation

![Screenshot 2021-11-28 at 23 21 25](https://user-images.githubusercontent.com/24797699/143776706-39e31603-57c0-444f-a22d-80bcdf31433f.png)

e.g.

![Screenshot 2021-11-28 at 23 26 23](https://user-images.githubusercontent.com/24797699/143776880-74f3750d-d90e-490b-82c4-fe849f4fa3ed.png)

2021-11-29 02:40 UTC, smk762 commented
![image](https://user-images.githubusercontent.com/35845239/143799647-6924b1ac-6c60-4f1a-9813-ba342db1341c.png)
Change "Enable" to "Next >"

![image](https://user-images.githubusercontent.com/35845239/143799808-d8937fcd-e52c-4f10-a329-2a4289d1df11.png)
Eyeball on right side of text input is hard to see

Seems when I try and delete wallet, it always says "wrong password", even if I use the password I can successfully log in with.

2021-12-02 16:37 UTC, tonymorony commented
app from this https://github.com/KomodoPlatform/atomicDEX-Desktop/actions/runs/1524893773 build not starting for me on OSX:


```
[23:36:09] [warning] [main.prerequisites.hpp:92] [735159]: QQmlApplicationEngine failed to load component
[23:36:09] [warning] [main.prerequisites.hpp:92] [735159]: qrc:/Dex/main.qml:411:5: Type App unavailable
[23:36:09] [warning] [main.prerequisites.hpp:92] [735159]: qrc:/Dex/App.qml:85:9: Type Dashboard unavailable
[23:36:09] [warning] [main.prerequisites.hpp:92] [735159]: qrc:/Dex/Screens/Dashboard.qml:134:13: Type Wallet unavailable
[23:36:09] [warning] [main.prerequisites.hpp:92] [735159]: qrc:/Dex/Wallet/Wallet.qml:54:5: Type Main unavailable
[23:36:09] [warning] [main.prerequisites.hpp:92] [735159]: qrc:/Dex/Wallet/Main.qml:347:34: Type SendModal unavailable
[23:36:09] [warning] [main.prerequisites.hpp:92] [735159]: qrc:/Dex/Wallet/SendModal.qml:10:1: Type BasicModal unavailable
[23:36:09] [warning] [main.prerequisites.hpp:92] [735159]: qrc:/Dex/Components/BasicModal.qml:7:1: Type DefaultModal unavailable
[23:36:09] [warning] [main.prerequisites.hpp:92] [735159]: qrc:/Dex/Components/DefaultModal.qml:12:28: Invalid alias reference. Unable to find id "background"
[23:36:09] [info] [main.prerequisites.hpp:486] [735159]: qml engine successfully loaded
[23:36:09] [error] [main.prerequisites.hpp:106] [735159]: sigabort received, cleaning mm2
No matching processes belonging to you were found
[23:36:09] [error] [main.prerequisites.hpp:112] [735159]: stacktrace:  0# main in /Applications/atomicdex-desktop.app/Contents/MacOS/atomicdex-desktop
 1# _sigtramp in /usr/lib/system/libsystem_platform.dylib
 2# QWindow::winId() const in /Applications/atomicdex-desktop.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
 3# main in /Applications/atomicdex-desktop.app/Contents/MacOS/atomicdex-desktop
 4# main in /Applications/atomicdex-desktop.app/Contents/MacOS/atomicdex-desktop
```

2021-12-02 16:43 UTC, tonymorony requested changes
can't start, since builds from other branches works I assume some problems with changes

2021-12-03 04:17 UTC, smk762 commented
> can't start, since builds from other branches works I assume some problems with changes

Also unable to start here, same errors in logs.

2021-12-03 07:40 UTC, ssakone commented
> 

should fixed now.

2021-12-03 10:02 UTC, tonymorony approved these changes

2021-12-03 15:12 UTC, SylEze approved these changes

2021-12-03 15:13 UTC, merged