add refund countdown
KomodoPlatform/atomicDEX-Desktop pull request #1716
Opened 2022-04-04 12:47 UTC by smk762

closes https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/620

2022-05-06 15:36 UTC, smk762 commented
To test this quicker, you can build mm2 from source with `cargo build --features custom-swap-locktime`
See https://github.com/KomodoPlatform/atomicDEX-API/pull/1252

If using the custom mm2, it needs to be running on both the maker and taker instances, otherwise there will be a "negtiate failed" error. I can put up some maker orders with the custom mm2 and/or provide testcoins if needed, just contact me on discord/keybase.

So far I've tested maker side countdown (start swap, then exit on taker node at the "maker wait and confirm" step), and will be testing taker side this weekend.

Once a swap fails, there will be a `until refund lock is released` countdown timer, which counts down until the payment_locktime` timestamp is reached.
![image](https://user-images.githubusercontent.com/35845239/167162925-111ddb41-41ad-4a49-8ab3-b511ff48caf0.png)

Sometimes there is a further delay, so a secondary countdown until the `wait_until` timestamp starts next. The refund will process before this timer expires - it is a "fallback" value.

https://user-images.githubusercontent.com/35845239/167165484-c39202d3-dc12-423d-a4d0-a81e7b160484.mp4

We might be able to better display this - users might not notice the fulltext of the timers and be confused why the (first) countdown that just reached zero is now (second) at an hour, or why when the (second) countdown still said 1 hour to go, the refund returned early. 

A perceived early refund is not too bad in terms of UX, but a countdown that jumps back up is not ideal. Might be worth adding some extra text and a green checkmark above the second timer to show that step has been reached but there is still one more step to go.

2022-05-07 03:51 UTC, cipig approved these changes

2022-05-11 13:11 UTC, Canialon submitted a review, later dismissed

2022-05-14 21:28 UTC, cipig submitted a review, later dismissed

2022-05-30 09:49 UTC, SylEze requested changes

2022-05-30 09:49 UTC, SylEze commented on atomic_defi_design/Dex/Components/DefaultModal.qml
> +    background: DexRectangle { radius: root.radius; color: Dex.CurrentTheme.floatingBackgroundColor }
Use DefaultRectangle

2022-05-30 09:49 UTC, SylEze commented on atomic_defi_design/Dex/Components/DefaultModal.qml
> +    Overlay.modal: DexRectangle { color: "#AA000000" }
Use DefaultRectangle

2022-05-30 09:49 UTC, SylEze commented on atomic_defi_design/Dex/Components/DexBusyIndicator.qml
> +    property int indicator_size: 64
camelCase

2022-05-30 09:49 UTC, SylEze commented on atomic_defi_design/Dex/Components/DexBusyIndicator.qml
> +    property int indicator_dot_size: 10
camelCase

2022-05-30 09:49 UTC, SylEze commented on atomic_defi_design/Dex/Components/DexCheckBox.qml
> +    Layout.preferredHeight: childrenRect.height
Same as above

2022-05-30 09:49 UTC, SylEze commented on atomic_defi_design/Dex/Components/DexScrollView.qml
> +    ScrollBar.horizontal: DexScrollBar
Use `DefaultScrollBar`

2022-06-01 03:49 UTC, smk762 commented on atomic_defi_design/Dex/Components/DexScrollView.qml
> +import QtQuick 2.15
I assume you mean DefaultScrollView

2022-06-06 10:15 UTC, SylEze requested changes

2022-06-06 10:15 UTC, SylEze commented on src/core/atomicdex/models/qt.orders.model.cpp
> +            SPDLOG_INFO("recover_funds_of_swap answer received: {}", body);
Use SPDLOG_DEBUG

2022-06-06 10:15 UTC, SylEze commented on src/core/atomicdex/models/qt.orders.model.cpp
> +        SPDLOG_INFO("recover_funds_of_swap request: {}", json_data.dump(-1));
Use SPDLOG_DEBUG

2022-06-06 10:15 UTC, SylEze commented on src/core/atomicdex/models/qt.orders.model.cpp
> +            {PaymentLockRole, "payment_lock"},
Make role name in camelCase because models are used by QML frontend

2022-06-06 10:15 UTC, SylEze commented on atomic_defi_design/Dex/Portfolio/Portfolio.qml
> +                            id: coin_search_field
camelCase

2022-06-06 10:15 UTC, SylEze commented on atomic_defi_design/Dex/Exchange/Trade/PriceLineSimplified.qml
> +    readonly property int line_scale: General.getComparisonScale(cex_price_diff)
camelCase

2022-06-06 10:15 UTC, SylEze commented on atomic_defi_design/Dex/Exchange/ProView/TradingInfo/SwapProgress.qml
>                          if (event.state === "Finished" && details.order_status === "failed") return DexTheme.redColor
Can you replace DexTheme usage by Dex.CurrentTheme please 🙏

2022-06-06 10:15 UTC, SylEze commented on atomic_defi_design/Dex/Exchange/ProView/TradingInfo/SwapProgress.qml
> +    property double payment_lock_countdown_time: -1    // First we wait for locktime expiry
camelCase

2022-06-06 10:15 UTC, SylEze commented on atomic_defi_design/Dex/Exchange/ProView/TradingInfo/SwapProgress.qml
> +    property double wait_until_countdown_time: -1      // Then we count down to 'wait_until' time
camelCase

2022-06-06 10:15 UTC, SylEze commented on atomic_defi_design/Dex/Exchange/ProView/TradingInfo/SwapProgress.qml
> +    property var last_event
camelCase

2022-06-11 13:19 UTC, cipig approved these changes

2022-06-12 22:46 UTC, SylEze approved these changes

2022-06-16 12:35 UTC, cipig approved these changes

2022-06-16 13:47 UTC, merged