hide explorer link if fresh wallet
KomodoPlatform/atomicDEX-Desktop pull request #1874
Opened 2022-07-15 18:00 UTC by smk762

Closes: https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1867

To Test:
- You should see a link for AVAX and AVX20 tokens, as we can't get history or them yet.
- For general utxo coins, for wallet where you have no balance or transactions, you will not see a link.

2022-07-16 19:47 UTC, Canialon commented
Should this link be removed? It still appears for me
![image](https://user-images.githubusercontent.com/77272165/179369837-5a04d4c9-980e-4b7e-a26a-65c92c80436a.png)
I tried CI builds for mac and windows

2022-07-18 09:11 UTC, SirSevenG requested changes
Hmmm, looks same for me (fresh wallet)
![image](https://user-images.githubusercontent.com/44422309/179480018-39cd6bdf-1e1e-4485-8521-c75b0d29b5db.png)
![image](https://user-images.githubusercontent.com/44422309/179480085-95e3081d-8bea-46e6-a084-5eae223e57b1.png)

2022-07-18 11:45 UTC, smk762 commented
I think it is fixed now - ignore AVAX, it actually does show history if available.

After this fix, you should only see the link on:
- Ubiq (UBQ)
- KuCoin (KCS)
- Harmony (ONE)
- SmartBCH (SBCH)

2022-07-20 10:09 UTC, SirSevenG approved these changes

2022-07-21 17:02 UTC, Canialon approved these changes

2022-07-22 11:09 UTC, tonymorony approved these changes

2022-07-22 11:09 UTC, merged