add form shortcuts, min vol input
KomodoPlatform/atomicDEX-Desktop pull request #1944
Opened 2022-08-24 05:07 UTC by smk762

closes: https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1941
closes: https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1459

https://user-images.githubusercontent.com/35845239/185878663-e3e08cd1-ee8e-45ce-ba29-f59bce54d54f.mp4

2022-08-25 08:26 UTC, SirSevenG approved these changes

2022-08-25 12:47 UTC, tonymorony commented
Thats a great feature, thank you!

1) I've noticed that inaccuracy accumulating when I press +1% (I assume it should be around 8% when I click 8 times but it's 8.32% what is quite huge diff)

https://user-images.githubusercontent.com/24797699/186668186-6d7e0a7e-6ee2-424e-84d2-6672569a2d19.mov

2) For a new user it might be not clear what -1% 0% 1% buttons means, it would be awesome to add a tooltip with clarification

2022-08-25 12:47 UTC, tonymorony requested changes
^^ it worth to double-check calculations, seems to be not precise

2022-08-25 12:52 UTC, smk762 commented
> ^^ it worth to double-check calculations, seems to be not precise

At the moment, the +1% is relative to currently input price, so it is compounding.
If you think its better to make it a consistent 1% relative to market, I can change that easy enough.

The only problem with this is if the coin has no cex price to calculate from. In this case, I can revert to compounding relative to price input field.

2022-08-25 13:04 UTC, smk762 commented
non-compounding is more intuitive, tho with tooltip explaining the compounding way for both priced and unpriced would be more consistent (otherwise long tooltip with conditionals).

Another alternative could be to remove those buttons for unpriced pairs (right now clicking the zero on an unpriced coin is pointless)

2022-08-29 12:23 UTC, tonymorony submitted a review, later dismissed

2022-08-29 22:51 UTC, Canialon requested changes
@smk762 this tip is a good idea, but they covered the field with information. So to see how the amount changed in this field I need to move out the mouse every time. Can you please replace the tips on the bottom of the buttons? I hope it will be better

<img width="392" alt="image" src="https://user-images.githubusercontent.com/77272165/187310351-1a5f0220-2daa-45cf-b692-d7ce08608c96.png">

________

I can set a negative price if I enter 0 and click the -1 button
<img width="310" alt="image" src="https://user-images.githubusercontent.com/77272165/187311934-bb306a8f-f3bb-48c2-809b-f83b9c026019.png">
Anyway, this swap will fail because of minimum price( `[{"error":"rpc:212] dispatcher_legacy:160] lp_ordermatch:3565] lp_ordermatch:3646] Price is too low, minimum is 0.00000001"}]` ). But I guess it would be good to eliminate the possibility of setting a negative value

2022-08-30 22:32 UTC, Canialon submitted a review, later dismissed

2022-08-31 15:47 UTC, tonymorony commented
found a bug I think:
I can see "Min volume" I've input when I deactivate "Use custom minimum trade amount" - I assume min trade volume shouldn't apply if deactivated:

https://user-images.githubusercontent.com/24797699/187721663-447a1ce0-cf1e-47f9-8b90-44bc9425a9b3.mov

2022-08-31 15:48 UTC, tonymorony requested changes
would be great to fix ^^

2022-08-31 16:14 UTC, smk762 commented on atomic_defi_design/Dex/Exchange/ProView/PlaceOrderForm/OrderForm.qml
> +            left_tooltip_text: "Minimum accepted trade equals 5% of your balance."
These buttons currently calculate the input as percentage of tradable balance - should I change them to calculate input as percentage of volume input?

2022-09-01 08:33 UTC, smk762 commented
I've also made the form stop bouncing around when you toggle the min volume field, get an error message or the "Order selected" box is displayed. Previously, when these became visible, it would shift other form elements - now everything should stay where it is when these things change between visible or hidden.

2022-09-01 22:25 UTC, Canialon approved these changes

2022-09-04 10:02 UTC, tonymorony approved these changes

2022-09-04 10:02 UTC, merged