show activated if activated
KomodoPlatform/atomicDEX-Desktop pull request #1996
Opened 2022-10-01 13:17 UTC by smk762

Fixes a bug where you can't enable a coin because when you do the API response in logs is 
```
[20:48:23] [debug] [mm2.service.cpp:1049] [922060]: error: bad answer json for enable/electrum details: {
    "error": "rpc:212] dispatcher_legacy:160] lp_commands_legacy:121] lp_coins:2270] Coin ZRX-PLG20 already initialized"
}
```
In this case, PR will make sure app adds coin to be visible in portfoilio.

2022-10-03 09:49 UTC, SirSevenG requested changes
On Ubuntu 20:
Started App
Enabled RICK in cli
Activated RICK in application
Opened RICK in dashboard, pressed faucet button
Application crashed

I don't see anything in logs tho, but it's reproducible scenario.

2022-10-04 08:30 UTC, smk762 commented
> On Ubuntu 20: Started App Enabled RICK in cli Activated RICK in application Opened RICK in dashboard, pressed faucet button Application crashed
> 
> I don't see anything in logs tho, but it's reproducible scenario.

Thanks - the cause of the crash was the RICK address not yet being set correctly (showing as `invalid ticker`) and not completely enabled.

2022-10-04 10:07 UTC, SirSevenG approved these changes

2022-10-05 03:39 UTC, smk762 commented
I've added some simple AtomicDEX-API bash scripts @ https://github.com/smk762/DragonhoundTools/tree/master/atomicdex/bash to assist with testing in CLI for PRs like this.

2022-10-05 06:42 UTC, Canialon approved these changes

2022-10-05 08:42 UTC, merged