0.5.7
KomodoPlatform/atomicDEX-Desktop pull request #2020
Opened 2022-10-21 13:40 UTC by ca333

2022-10-24 12:18 UTC, DeckerSU submitted a review, later dismissed
LGTM.

**p.s.** PR assume version bump to `0.5.7`, but `get_version()`, `get_raw_version()`, etc. from `version.hpp` still returning old version `0.5.6`.
**p.p.s.** PR verified from a "security side", logic and implementation errors didn't tested for obvious reasons (time, deep-in, etc.)

2022-10-26 10:16 UTC, SylEze requested changes

2022-10-26 10:16 UTC, SylEze commented on atomic_defi_design/Dex/Components/ZcashParamsModal.qml
> +            function onCombinedDownloadStatusChanged()
This implementation is slow and error prone, it should be done in C++ where there is strong type safety: put at least a todo for next releases

2022-10-26 10:16 UTC, SylEze commented on atomic_defi_design/Dex/Exchange/ProView/PlaceOrderForm/Main.qml
> +            DexLabel
Use `Dex.Text`.

2022-10-26 10:16 UTC, SylEze commented on src/app/app.cpp
> +                if (coin_parent_info.ticker != "")
weird. parent's ticker should not empty if it has been found.

2022-11-03 11:30 UTC, SylEze requested changes

2022-11-03 11:30 UTC, SylEze commented on atomic_defi_design/Dex/Components/CoinMenu.qml
> +            return General.canDisable(ticker, progress)
canDisable does not accept two parameters
And even if it's the case it should not need a ZHTLC `progress` param

2022-11-03 11:30 UTC, SylEze commented on atomic_defi_design/Dex/Components/CoinMenu.qml
> +            let progress = General.zhtlcActivationProgress(current_ticker_infos.activation_status, ticker)
ZHTLC should not be called when the current ticker is not a ZHTLC asset...
Put this statement inside the if below ?

2022-11-03 11:30 UTC, SylEze commented on atomic_defi_design/Dex/Components/CoinMenu.qml
> +            let progress = General.zhtlcActivationProgress(current_ticker_infos.activation_status, ticker)
Maybe we can put the zhtlc logic inside the canDisable function directly

2022-11-03 11:30 UTC, SylEze commented on atomic_defi_design/Dex/Exchange/ProView/PlaceOrderForm/OrderFormSubfield.qml
> +    property alias  fiat_value: _fiat_label.text_value
Coding style is wrong: use camelCase

2022-11-04 15:06 UTC, smk762 commented
![image](https://user-images.githubusercontent.com/35845239/200008301-9ba25734-bf71-4c53-a7a4-dbf71633df2d.png)
SLP token mainnet confirmed

2022-11-14 09:08 UTC, SylEze approved these changes

2022-11-14 09:12 UTC, tonymorony commented on CMakeLists.txt
> +            URL http://195.201.0.6/mm2.1/mm2-1e1338d2d-Darwin-Release.zip)
we need API release from sec env before merge

2022-11-18 15:13 UTC, smk762 approved these changes
Thanks to all involved with this mammoth release! :revolving_hearts:

2022-11-18 16:35 UTC, SirSevenG approved these changes

2022-11-18 18:27 UTC, DeckerSU approved these changes

2022-11-20 22:25 UTC, merged