Display fiat equivalents when sending coins
KomodoPlatform/atomicDEX-Desktop pull request #506
Opened 2020-10-16 14:23 UTC by SylEze

Old behavior:
![send_coins_without_fiat_eqivalent](https://user-images.githubusercontent.com/14373103/96270256-aff85f80-0fcb-11eb-922a-a3bb9f679881.png)

New behavior:
<img width="650" alt="send_coins_with_fiat_equivalent" src="https://user-images.githubusercontent.com/14373103/96270272-b4bd1380-0fcb-11eb-9396-8ca2eaa80cac.png">

2020-10-16 15:48 UTC, Milerius commented on src/atomicdex/pages/qt.wallet.page.cpp
> +                auto fee = j_out["withdraw_answer"]["fee_details"]["amount"];
Spurious automatic conversion to `std::string` will rather prefer to use `get<std::string>()` to be sure.

2020-10-16 16:21 UTC, naezith commented
Seems good to me!

2020-10-16 17:01 UTC, tonymorony requested changes
looks like USD prices calculating not correct in some cases (was my first test to broadcast KMD)
unfortunately atm 1 KMD cost a bit less than 41$ :)

![image](https://user-images.githubusercontent.com/24797699/96287195-beff0200-100b-11eb-8d96-975ba0a0a76e.png)
![image](https://user-images.githubusercontent.com/24797699/96287198-c0302f00-100b-11eb-9a89-0001e51ec500.png)

2020-10-16 22:01 UTC, SylEze commented
> looks like USD prices calculating not correct in some cases (was my first test to broadcast KMD)
> unfortunately atm 1 KMD cost a bit less than 41$ :)
> 
> ![image](https://user-images.githubusercontent.com/24797699/96287195-beff0200-100b-11eb-8d96-975ba0a0a76e.png)
> ![image](https://user-images.githubusercontent.com/24797699/96287198-c0302f00-100b-11eb-9a89-0001e51ec500.png)

I will check the function which does the conversion in the backend and the one which formats the result in the front-end

2020-10-17 10:52 UTC, SylEze commented
@tonymorony Can you try again with the last pull and tell me if it's working now please ?

2020-10-17 13:26 UTC, tonymorony approved these changes
lgtm now, thanks!

2020-10-17 13:27 UTC, merged