Listing Ciphscoin
KomodoPlatform/atomicDEX-Desktop pull request #934
Opened 2021-05-22 04:54 UTC by ciphs

2021-05-23 12:29 UTC, Milerius commented on qml.qrc
> +		<file>atomic_defi_design/assets/images/coins/ciphs.png</file>
spurious alignment

2021-05-23 12:29 UTC, Milerius commented on atomic_defi_design/qml/Constants/Style.qml
> +                                          "CIPHS": "#ecd900",
Hexadecimal character need to be uppercase

2021-05-26 08:59 UTC, cipig approved these changes

2021-05-27 07:18 UTC, Milerius requested changes
see my comment

2021-06-01 10:39 UTC, ciphs reviewed
fix

2021-06-01 20:34 UTC, merged