feat(Logout_confirmation): Add logout confirmation dialog
KomodoPlatform/atomicDEX-Desktop pull request #970
Opened 2021-06-10 12:00 UTC by ssakone

2021-06-11 05:00 UTC, smk762 commented
When attempting to log out via header bar, nothing happens.
When attempting to logout from settings, modal disappears, but app remains logged in.
No indication of cause in logs.

https://user-images.githubusercontent.com/35845239/121633153-dc11a500-cab4-11eb-8926-1f417f844ace.mp4

2021-06-15 08:34 UTC, tonymorony requested changes
@ssakone logout doesn't work at all on this branch, please re-check

2021-06-15 09:09 UTC, ssakone commented
ok

2021-06-17 12:57 UTC, ssakone commented
> When attempting to log out via header bar, nothing happens.
> When attempting to logout from settings, modal disappears, but app remains logged in.
> No indication of cause in logs.
> no_logout.mp4

pls tell me what os, because on linux i have this issue

2021-06-18 09:19 UTC, tonymorony commented
The functionality works for me now, thanks!

@smk762 could you please re-test and advice on wording there:

![image](https://user-images.githubusercontent.com/24797699/122538524-d8e85d00-d050-11eb-90e3-2e8d87ca2e82.png)

2021-06-20 10:40 UTC, smk762 commented on atomic_defi_design/qml/Settings/SettingModal.qml
> +        Qaterial.DialogManager.showDialog({title: qsTr("Logout request"),text: qsTr("Confirm logout request to disconnect!!"),iconSource: Qaterial.Icons.logout,standardButtons: Dialog.Yes | Dialog.Ca
Change title to "Confirm Logout"
Change text to "Are you sure you want to log out?"

2021-06-21 16:27 UTC, tonymorony approved these changes

2021-06-21 16:27 UTC, merged